version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    environment:
      - PORT=8080
      - ENV=development
      - DATABASE_URL=postgres://postgres:dart3@database:5433/dart3
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_REGION=
      - AUTH0_CLIENT_ID=
      - AUTH0_CLIENT_SECRET=
      - AUTH0_DOMAIN=
      - AUTH0_AUDIENCE=
      - CLIENT_URL=http://localhost:4200
      - LOG_LEVEL=debug
    image: dart3-api
    expose:
      - 8080
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/app
      - ./nodemon.json:/app/nodemon.json
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:11.8
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dart3
      POSTGRES_PASSWORD: dart3
    volumes:
      - dart3_dbdata:/var/lib/postgresql/data/
    ports:
      - 5433:5433

volumes:
  dart3_dbdata: