version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/ecr.dockerfile
      args:
        - PORT=$PORT
        - ENV=$ENV
        - DATABASE_URL=$DATABASE_URL
        - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
        - AWS_SECRET_KEY=$AWS_SECRET_KEY
        - AWS_REGION=$AWS_REGION
        - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
        - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
        - AUTH0_URL=$AUTH0_URL
        - AUTH0_AUDIENCE=$AUTH0_AUDIENCE
        - JACKPOT_GEM=$JACKPOT_GEM
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
 