version: '3.7'

services:
  api:
    environment:
      - PORT=$PORT
      - ENV=$ENV
      - DATABASE_URL=$DATABASE_URL
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_KEY=$AWS_SECRET_KEY
      - AWS_REGION=$AWS_REGION
      - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
      - AUTH0_API_AUDIENCE=$AUTH0_API_AUDIENCE
      - AUTH0_API_URL=$AUTH0_API_URL
      - AUTH0_OAUTH_URL=$AUTH0_OAUTH_URL
    build:
      context: .
      dockerfile: ./docker/ecr.dockerfile
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
 